/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace SimpleMosiServer
{
  public enum TGait
  {
    standing = 0,
    walking = 1,
    running = 2,
  }
}
