apiVersion: v1
kind: Pod
metadata:
  name: train-env-v2
  namespace: chbh01
spec:
  containers:
  - name: test
    image: dmrub/tensorflow-1.12.0-notebook-gpu:v0.4.0
    volumeMounts:
        - mountPath: /tf
          name: volume-0-chbh01
  volumes:
    - name: volume-0-chbh01
#      hostPath:
#        path: C:\Users\chira\OneDrive\Documents\Uni\Thesis\VCS-MOSI-DEV-VINN
      persistentVolumeClaim:
        claimName: chbh01-workspace
  restartPolicy: Never
  hostNetwork: true
  dnsPolicy: Default


