apiVersion: batch/v1
kind: Job
metadata:
  name: test
  namespace: chbh01
spec:
  template:
    spec:
      containers:
      - name: test
        image: dmrub/tensorflow-1.12.0-notebook-gpu:v0.4.0
        command: ["/bin/bash", "-c"]
#        args: ["cd /tf; nvidia-smi >> test.txt"]
        args: ["cd /tf/mosi_dev_vinn/mosi_dev_vinn;  python main.py >> mann_run_1.txt"]
        resources:
            limits:
                nvidia.com/gpu: 1
        volumeMounts:
            - mountPath: /tf
              name: volume-0-chbh01
      volumes:
        - name: volume-0-chbh01
          persistentVolumeClaim:
            claimName: chbh01-workspace
      restartPolicy: Never
  backoffLimit: 1
  